package ru.sdmitriy612.clientapp.commands;

import ru.sdmitriy612.interactors.Request;
import ru.sdmitriy612.interactors.Response;


/**
 * Abstract class representing a command in the program.
 * <p>
 * A command has a description, a command type, and an execution method.
 * </p>
 */
public abstract class Command {

    protected Command(){
    }

    /**
     * Executes the command with the given request.
     *
     * @param request the request to be processed by the command
     * @return the response generated by executing the command
     */
    public abstract Response execute(Request request);

}
